version: '3.7'

volumes:
  database:
  cms:

services:

  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  cms:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - cms:/var/www/html/wp-content
      - ./backend:/var/www/html/wp-content/themes/nuxt
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
